# Generated by Django 3.2.9 on 2025-02-27 00:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='catalogada',
            name='codigo_antes',
            field=models.CharField(max_length=10, null=True, verbose_name='Código antes'),
        ),
        migrations.AddField(
            model_name='documento',
            name='codigo_antes',
            field=models.CharField(max_length=10, null=True, verbose_name='Código antes'),
        ),
        migrations.AlterField(
            model_name='catalogada',
            name='conservadora_intermediaria_nascimento',
            field=models.CharField(max_length=500, verbose_name='Forma conservadora da unidade administrativa intermediária de nascimento'),
        ),
        migrations.AlterField(
            model_name='catalogada',
            name='conservadora_maior_nascimento',
            field=models.CharField(max_length=500, verbose_name='Forma conservadora da unidade administrativa maior de nascimento'),
        ),
        migrations.AlterField(
            model_name='catalogada',
            name='conservadora_menor_nascimento',
            field=models.CharField(max_length=500, verbose_name='Forma conservadora da unidade administrativa menor do local de nascimento'),
        ),
        migrations.AlterField(
            model_name='catalogada',
            name='perfil_documental',
            field=models.CharField(max_length=200, verbose_name='Perfil documental da catalogada'),
        ),
        migrations.AlterField(
            model_name='catalogada',
            name='publicar',
            field=models.CharField(choices=[('Sim', 'Sim'), ('Não', 'Não')], default='Não', max_length=3),
        ),
        migrations.AlterField(
            model_name='catalogada',
            name='unidade_intermediaria_nascimento',
            field=models.CharField(max_length=500, verbose_name='Unidade administrativa intermediária do local de nascimento'),
        ),
        migrations.AlterField(
            model_name='catalogada',
            name='unidade_maior_nascimento',
            field=models.CharField(max_length=500, verbose_name='Unidade administrativa maior do local de nascimento'),
        ),
        migrations.AlterField(
            model_name='catalogada',
            name='unidade_menor_nascimento',
            field=models.CharField(max_length=500, verbose_name='Unidade administrativa menor do local de nascimento'),
        ),
        migrations.AlterField(
            model_name='documento',
            name='ano_inferencia',
            field=models.CharField(max_length=500, verbose_name='Ano de escrita do documento inferido'),
        ),
        migrations.AlterField(
            model_name='documento',
            name='arquivo_guarda',
            field=models.CharField(max_length=500, verbose_name='Arquivo de guarda'),
        ),
        migrations.AlterField(
            model_name='documento',
            name='cronologica_final_inferencia',
            field=models.CharField(max_length=500, verbose_name='Datação cronológica final inferida'),
        ),
        migrations.AlterField(
            model_name='documento',
            name='cronologica_inicial_inferencia',
            field=models.CharField(max_length=500, verbose_name='Datação cronológica inicial inferida'),
        ),
        migrations.AlterField(
            model_name='documento',
            name='estado_civil',
            field=models.CharField(max_length=500, verbose_name='Estado civil da catalogada no documento'),
        ),
        migrations.AlterField(
            model_name='documento',
            name='perfil_documental',
            field=models.CharField(max_length=500, verbose_name='Perfil documental da catalogada'),
        ),
        migrations.AlterField(
            model_name='documento',
            name='publicar',
            field=models.CharField(choices=[('Sim', 'Sim'), ('Não', 'Não')], default='Não', max_length=3),
        ),
        migrations.AlterField(
            model_name='documento',
            name='subtipo_documento',
            field=models.CharField(max_length=500, verbose_name='Subtipo de documento'),
        ),
        migrations.AlterField(
            model_name='documento',
            name='tipo_documento',
            field=models.CharField(max_length=500, verbose_name='Tipo de documento'),
        ),
    ]
